version: '3.8'
services:
  backend:
    build: .
    command: daphne -b 0.0.0.0 -p 8080 asgi:application
    working_dir: /docker-server/soriboard_backend
    volumes:
      - .:/docker-server/soriboard_backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
