name: Python Black format check

on: [push, pull_request]

jobs:
  black-format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install black
      run: pip install black
    - name: Check formatting
      run: black --check .
